version: '3.7'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro

  hass-configurator:
    container_name: hassconf
    image: causticlab/hass-configurator-docker
    restart: unless-stopped
    environment:
      - HC_BASEPATH=/hass-config
      - HC_DIRSFIRST=true
    ports:
      - "3218:3218/tcp"
    volumes:
      - ./fileeditor:/config
      - ./homeassistant:/hass-config

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /etc/mosquitto/docker-mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/mosquitto/conf.d:/mosquitto/config/conf.d
      - /var/lib/mosquitto:/mosquitto/data
      - /var/log/mosquitto:/mosquitto/log
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - /mnt/usbssd:/srv
      - /etc/filebrowser:/config
    command: ["--noauth"]

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8089:80"
    volumes:
      - /mnt/usbssd/Media:/var/www/html
    restart: unless-stopped
