- id: '1713959629455'
  alias: Ворота
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_tasmota4
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_tasmota4
  mode: single
- id: '1713959864031'
  alias: Котел. Эмуляция кнопки
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_9
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1713963931921'
  alias: Котел. Включение отопления
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.boiler
    to: 'off'
    from: 'on'
  - platform: state
    entity_id:
    - input_boolean.boiler
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1714061753461'
  alias: Мониторинг воды
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.tasmota_counter_c1
  condition: []
  action:
  - service: counter.increment
    metadata: {}
    data: {}
    target:
      entity_id: counter.water
  mode: single
- id: '1714065051725'
  alias: Котел. Автоматическое включение по мощности
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_9
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: state
    entity_id: climate.otoplenie
    state: heat
  - condition: state
    entity_id: input_boolean.boiler
    state: 'on'
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power
      below: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_2
      below: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_3
      below: 2000
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1714065211948'
  alias: Котел. Автоматическое выключение по мощности
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_9
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: state
    entity_id: climate.otoplenie
    state: heat
  - condition: state
    entity_id: input_boolean.boiler
    state: 'off'
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power
      above: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_2
      above: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_3
      above: 2000
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1714070196345'
  alias: Нотификации
  description: ''
  trigger:
  - platform: time
    at: 01:50:00
  condition: []
  action:
  - service: notify.me
    data:
      message: 'Электроэнергия: {{ (float(states(''sensor.tasmota_energy_today''))
        + float(states(''sensor.tasmota_energy_today_2'')) + float(states(''sensor.tasmota_energy_today_3'')))
        | round(1) }} кВт

        Вода: {{ states(''counter.water'') }} л

        '
  - service: counter.reset
    metadata: {}
    data: {}
    target:
      entity_id: counter.water
  mode: single
- id: '1714286749734'
  alias: Шторы. Открытие Кухня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_kitchen
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 93
    target:
      entity_id: cover.lumi_lumi_curtain_cover_3
  mode: single
- id: '1714287233643'
  alias: Шторы. Открытие зал
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_hall
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 93
    target:
      entity_id: cover.lumi_lumi_curtain_cover
  mode: single
- id: '1714287359840'
  alias: Шторы. Открытие спальня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_bedroom
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 70
    target:
      entity_id: cover.lumi_lumi_curtain_cover_2
  mode: single
- id: '1714293460781'
  alias: Ping устройств
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_9
    - switch.tasmota_11
    - switch.tasmota_7
    - switch.tasmota_5
    - switch.tasmota_tasmota2
    - switch.tasmota_8
    - switch.tasmota_6
    - light.tasmota
    - light.light_kitchen_street
    - sensor.tasmota_energy_power
    - switch.tasmota_4
    - sensor.tasmota_energy_power_2
    - sensor.tasmota_energy_power_3
    - switch.lumi_lumi_curtain_switch
    - switch.lumi_lumi_curtain_switch_3
    - switch.lumi_lumi_curtain_switch_2
    - sensor.zigbee_temperature
    - binary_sensor.lumi_lumi_sensor_wleak_aq1_moisture
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - input_boolean.irrigate_availeble
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.me
    data:
      message: Некоторые устройства не доступны
  mode: single
- id: '1714395961414'
  alias: Автополив. MQTT hook
  description: 'MQTT listener which receives response about triggered irrigation command. '
  trigger:
  - platform: mqtt
    topic: hunter/X-CORE/result
  condition: []
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.zone_action_result
      value: '{{ trigger.payload_json.action }}'
  mode: single
- id: '1714396039835'
  alias: Автополив. Включение вечером
  description: ''
  trigger:
  - platform: time
    at: input_datetime.irrigate_evning
  condition:
  - condition: state
    entity_id: input_boolean.irrigate_evning
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip_evning
    state: 'off'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.irrigate_zone
      option: '2'
  - if:
    - condition: state
      entity_id: input_boolean.irrigate_skip_evning
      state: 'on'
    then:
    - stop: ''
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  - wait_for_trigger:
    - platform: state
      entity_id:
      - switch.irrigate_lawn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 10
  - service: input_select.select_option
    data_template:
      entity_id: input_select.irrigate_zone
      option: '3'
  - if:
    - condition: state
      entity_id: input_boolean.irrigate_skip_evning
      state: 'on'
    then:
    - stop: ''
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  - wait_for_trigger:
    - platform: state
      entity_id:
      - switch.irrigate_lawn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 10
  - service: input_select.select_option
    data_template:
      entity_id: input_select.irrigate_zone
      option: '4'
  - if:
    - condition: state
      entity_id: input_boolean.irrigate_skip_evning
      state: 'on'
    then:
    - stop: ''
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  - wait_for_trigger:
    - platform: state
      entity_id:
      - switch.irrigate_lawn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 10
  - service: input_select.select_option
    data_template:
      entity_id: input_select.irrigate_zone
      option: '1'
  - if:
    - condition: state
      entity_id: input_boolean.irrigate_skip_evning
      state: 'on'
    then:
    - stop: ''
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  mode: single
- id: '1714542925010'
  alias: Автополив. Отключение таймера
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.irrigation_time_remaining
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  mode: single
- id: '1714552765247'
  alias: Автополив. Переключить пропустить сегодня
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.irrigate_skip_evning
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.irrigate_skip_morning
  mode: single
- id: '1714579193096'
  alias: Автополив. Ping
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition: []
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.irrigate_availeble
  - service: rest_command.ping_autopolive
    response_variable: traefik_response
    data: {}
  - if:
    - condition: template
      value_template: '{{ traefik_response[''status''] == 200 }}'
    then:
    - service: input_boolean.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.irrigate_availeble
    else:
    - service: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.irrigate_availeble
  mode: single
- id: '1714584809649'
  alias: Уборка. Кухня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.clean_kitchen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments: 5
    target:
      entity_id:
      - vacuum.zhorik
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.clean_kitchen
  mode: single
- id: '1714988828391'
  alias: Фумигатор
  description: ''
  trigger:
  - platform: time
    at: input_datetime.fumigator_time
  condition:
  - condition: state
    entity_id: input_boolean.fumigator_enabled
    state: 'on'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.lumi_lumi_plug_maeu01_switch
  - delay: '{{ states(''input_number.fumigator_timer'') | multiply(3600) | int }}'
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.lumi_lumi_plug_maeu01_switch
  mode: single
- id: '1714999615150'
  alias: Потребление электроэнергии
  description: ''
  trigger:
  - platform: time
    at: 01:50:00
  condition: []
  action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{ float(states(''input_number.energy_total'')) + (float(states(''sensor.tasmota_energy_today''))
        + float(states(''sensor.tasmota_energy_today_2'')) + float(states(''sensor.tasmota_energy_today_3'')))
        }}'
    target:
      entity_id: input_number.energy_total
  mode: single
- id: '1719852476111'
  alias: Автополив. Включение утром
  description: ''
  trigger:
  - platform: time
    at: input_datetime.irrigate_morning
  condition:
  - condition: state
    entity_id: input_boolean.irrigate_morning
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip_morning
    state: 'off'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.irrigate_zone
      option: '2'
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn
  mode: single
- id: '1724849977055'
  alias: Свет коридор app
  description: ''
  trigger:
  - event_type: ios.action_fired
    event_data:
      actionID: 9CDFA50D-3808-451F-88CB-DB82ECE619B5
    platform: event
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_8
  mode: single
- id: '1724850283575'
  alias: Свет гостевая app
  description: ''
  trigger:
  - event_data:
      actionID: 2DC2D0A0-BC5F-4532-AAC2-DB9A038CD40D
    platform: event
    event_type: ios.action_fired
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_11
  mode: single
- id: '1724850441673'
  alias: Свет кухня app
  description: ''
  trigger:
  - event_data:
      actionID: D7998894-CE4E-4459-9B29-659CF527BB13
    platform: event
    event_type: ios.action_fired
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_2
  mode: single
- id: '1724850559017'
  alias: Свет гостиная app
  description: ''
  trigger:
  - event_type: ios.action_fired
    event_data:
      actionID: FAC56F0C-2DF9-4A73-B988-8FC400FB7227
    platform: event
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_tasmota2
  mode: single
- id: '1724850619917'
  alias: Свет спальня app
  description: ''
  trigger:
  - event_type: ios.action_fired
    event_data:
      actionID: 1B3AD778-F24D-461A-9DF1-E082F6FA7FCD
    platform: event
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_tasmota3
  mode: single
- id: '1724850676231'
  alias: Свет детская app
  description: ''
  trigger:
  - event_type: ios.action_fired
    event_data:
      actionID: 02D75916-0836-462A-9FFD-BE78E83D9C4F
    platform: event
  condition: []
  action:
  - service: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_7
  mode: single
- id: '1724850917969'
  alias: Кондиционер app
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: 847DBF82-3269-4464-955F-95CE77D984FF
  condition: []
  action:
  - if:
    - condition: device
      device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: is_hvac_mode
      hvac_mode: 'off'
    then:
    - device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: set_hvac_mode
      hvac_mode: cool
    else:
    - device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1725869765920'
  alias: Шторы. Закрытие Кухня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_kitchen
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      entity_id: cover.lumi_lumi_curtain_cover_3
  mode: single
- id: '1725872336316'
  alias: Шторы. Закрытие Зал
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_hall
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      device_id: 438c446d2c617f86871757130e4f90d8
  mode: single
- id: '1725872877068'
  alias: Шторы. Закрытие Спальня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_bedroom
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      entity_id: cover.lumi_lumi_curtain_cover_2
  mode: single
