- id: '1713959629455'
  alias: Ворота
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_tasmota4
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_tasmota4
  mode: single
- id: '1713959864031'
  alias: Котел. Эмуляция кнопки
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.tasmota_9
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1713963931921'
  alias: Котел. Включение отопления
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.boiler
    to: 'off'
    from: 'on'
  - platform: state
    entity_id:
    - input_boolean.boiler
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
  mode: single
- id: '1714061753461'
  alias: Мониторинг воды
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.tasmota_counter_c1
  condition: []
  action:
  - service: counter.increment
    metadata: {}
    data: {}
    target:
      entity_id: counter.water
  mode: single
- id: '1714065051725'
  alias: Котел. Автоматическое включение по мощности
  description: ''
  triggers:
  - entity_id:
    - switch.tasmota_9
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: state
  conditions:
  - condition: state
    entity_id: climate.otoplenie
    state: heat
  - condition: state
    entity_id: input_boolean.boiler
    state: 'on'
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power
      below: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_2
      below: 2000
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_3
      below: 2000
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
    action: switch.turn_on
  - action: notify.me
    metadata: {}
    data:
      message: Повторная попытка включения котла
  mode: single
- id: '1714065211948'
  alias: Котел. Автоматическое выключение по мощности
  description: ''
  triggers:
  - entity_id:
    - switch.tasmota_9
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: state
  conditions:
  - condition: state
    entity_id: climate.otoplenie
    state: heat
  - condition: state
    entity_id: input_boolean.boiler
    state: 'off'
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power
      above: 1900
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_2
      above: 1700
    - condition: numeric_state
      entity_id: sensor.tasmota_energy_power_3
      above: 1900
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_9
    action: switch.turn_on
  - action: notify.me
    metadata: {}
    data:
      message: Повторная попытка выключения котла
  mode: single
- id: '1714070196345'
  alias: Нотификации. Потребление
  description: ''
  triggers:
  - at: 01:50:00
    trigger: time
  conditions: []
  actions:
  - data:
      message: 'Электроэнергия: {{ (float(states(''sensor.tasmota_energy_today''))
        + float(states(''sensor.tasmota_energy_today_2'')) + float(states(''sensor.tasmota_energy_today_3'')))
        | round(1) }} кВт

        Вода: {{ states(''counter.water'') }} л

        '
    action: notify.me
  - metadata: {}
    data: {}
    target:
      entity_id: counter.water
    action: counter.reset
  mode: single
- id: '1714287233643'
  alias: Шторы. Открытие зал
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_hall
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 93
    target:
      entity_id: cover.lumi_lumi_curtain_cover
  mode: single
- id: '1714287359840'
  alias: Шторы. Открытие спальня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_bedroom
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 70
    target:
      entity_id: cover.lumi_lumi_curtain_cover_2
  mode: single
- id: '1714293460781'
  alias: Нотификации. Ping устройств
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.tasmota_9
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_5
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_11
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_7
      state: unavailable
    - condition: state
      entity_id: light.4ch_tasmota2
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_6
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_8
      state: unknown
    - condition: state
      entity_id: light.tasmota
      state: unavailable
    - condition: state
      entity_id: light.light_kitchen_street
      state: unavailable
    - condition: state
      entity_id: sensor.tasmota_energy_apparentpower
      state: unavailable
    - condition: state
      entity_id: sensor.tasmota_energy_current_2
      state: unavailable
    - condition: state
      entity_id: sensor.tasmota_energy_power_3
      state: unavailable
    - condition: state
      entity_id: switch.lumi_lumi_curtain_switch
      state: unavailable
    - condition: state
      entity_id: switch.lumi_lumi_curtain_switch_3
      state: unavailable
    - condition: state
      entity_id: switch.lumi_lumi_curtain_switch_2
      state: unavailable
    - condition: state
      entity_id: sensor.zigbee_humidity
      state: unavailable
    - condition: state
      entity_id: switch.tasmota_12
      state: unavailable
    - condition: state
      entity_id: sensor.tze284_kyyu8rbj_ts0601_glubina_zhidkosti
      state: unavailable
  actions:
  - data:
      message: "Устройства не доступны{{ '\\n' }} {%- for entity in state_attr('sensor.unavailable_entities','entities')
        -%}\n    - {{ entity }}{%- if not loop.last -%}{{ '\\n' }}{%- endif -%}\n{%-
        endfor -%}\n"
    action: notify.me
  mode: single
- id: '1714395961414'
  alias: Автополив. MQTT hook
  description: 'MQTT listener which receives response about triggered irrigation command. '
  trigger:
  - platform: mqtt
    topic: hunter/X-CORE/result
  condition: []
  action:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.zone_action_result
      value: '{{ trigger.payload_json.action }}'
  mode: single
- id: '1714396039835'
  alias: Автополив. Газон. Включение вечером
  description: ''
  triggers:
  - at: input_datetime.irrigate_gas_evning
    trigger: time
  conditions:
  - condition: state
    entity_id: input_boolean.irrigate_evning_gas
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn_gas
  mode: single
- id: '1714542925010'
  alias: Автополив. Отключение таймера
  description: ''
  triggers:
  - event_type: timer.finished
    event_data:
      entity_id: timer.irrigation_time_remaining
    trigger: event
  conditions: []
  actions:
  - data: {}
    target:
      entity_id:
      - switch.irrigate_lawn_gas
      - switch.irrigate_lawn_kust_terrace
      - switch.irrigate_lawn_kust_facade
      - switch.irrigate_lawn_gradki
    action: switch.turn_off
  mode: single
- id: '1714552765247'
  alias: Автополив. Переключить пропустить сегодня
  description: ''
  triggers:
  - at: 06:00:00
    trigger: time
  conditions: []
  actions:
  - action: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.irrigate_skip
  mode: single
- id: '1714579193096'
  alias: Нотификации. Автополив
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions: []
  actions:
  - response_variable: traefik_response
    data: {}
    action: rest_command.ping_autopolive
  - if:
    - condition: template
      value_template: '{{ traefik_response[''status''] != 200 }}'
    then:
    - data:
        message: Автополив недоступен
      action: notify.me
  mode: single
- id: '1714584809649'
  alias: Уборка. Кухня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.clean_kitchen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: dreame_vacuum.vacuum_clean_segment
    data:
      segments: 5
    target:
      entity_id:
      - vacuum.zhorik
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.clean_kitchen
  mode: single
- id: '1714988828391'
  alias: Фумигатор
  description: ''
  triggers:
  - at: input_datetime.fumigator_time
    trigger: time
  conditions:
  - condition: state
    entity_id: input_boolean.fumigator_enabled
    state: 'on'
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.lumi_lumi_plug_maeu01_switch
    action: switch.turn_on
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_10
  - delay: '{{ states(''input_number.fumigator_timer'') | multiply(3600) | int }}'
  - metadata: {}
    data: {}
    target:
      entity_id: switch.lumi_lumi_plug_maeu01_switch
    action: switch.turn_off
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_10
  mode: single
- id: '1714999615150'
  alias: Потребление электроэнергии
  description: ''
  trigger:
  - platform: time
    at: 01:50:00
  condition: []
  action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{ float(states(''input_number.energy_total'')) + (float(states(''sensor.tasmota_energy_today''))
        + float(states(''sensor.tasmota_energy_today_2'')) + float(states(''sensor.tasmota_energy_today_3'')))
        }}'
    target:
      entity_id: input_number.energy_total
  mode: single
- id: '1719852476111'
  alias: Автополив. Газон. Включение утром
  description: ''
  triggers:
  - at: input_datetime.irrigate_morning
    trigger: time
  conditions:
  - condition: state
    entity_id: input_boolean.irrigate_morning_gas
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn_gas
  mode: single
- id: '1724850917969'
  alias: Кондиционер app
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: 847DBF82-3269-4464-955F-95CE77D984FF
  condition: []
  action:
  - if:
    - condition: device
      device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: is_hvac_mode
      hvac_mode: 'off'
    then:
    - device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: set_hvac_mode
      hvac_mode: cool
    else:
    - device_id: b4d1986e9170f928dbff31caebefb162
      domain: climate
      entity_id: 734491128fd2c53bc85f36b0c5df86da
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1725869765920'
  alias: Шторы. Закрытие Кухня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_kitchen
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      entity_id: cover.lumi_lumi_curtain_cover_3
  mode: single
- id: '1725872336316'
  alias: Шторы. Закрытие Зал
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_hall
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      device_id: 438c446d2c617f86871757130e4f90d8
  mode: single
- id: '1725872877068'
  alias: Шторы. Закрытие Спальня
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.curtain_bedroom
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: cover.set_cover_position
    metadata: {}
    data:
      position: 0
    target:
      entity_id: cover.lumi_lumi_curtain_cover_2
  mode: single
- id: '1739696318879'
  alias: Нотификации. Недоступность датчика температуры
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions:
  - condition: state
    entity_id: sensor.zigbee_temperature
    state: unavailable
  actions:
  - action: notify.me
    metadata: {}
    data:
      message: Датчик температуры недоступен
  mode: single
- id: '1739696578326'
  alias: Нотификации. Уровень заряда батарейки
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /12
  conditions:
  - condition: numeric_state
    entity_id: sensor.zigbee_battery
    below: 10
  actions:
  - action: notify.me
    data:
      message: Садится батарейка
  mode: single
- id: '1739988498478'
  alias: Нотификации. Ошибка котла высокая температура
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /1
  conditions:
  - condition: numeric_state
    entity_id: sensor.zigbee_temperature
    above: 26
  - condition: state
    entity_id: climate.otoplenie
    state: heat
  actions:
  - action: notify.me
    metadata: {}
    data:
      message: Высокая температура в доме
  mode: single
- id: '1745090412881'
  alias: Автополив. Грядки.
  description: ''
  triggers:
  - trigger: time
    at: input_datetime.irrigate_gradki
  conditions:
  - condition: state
    entity_id: input_boolean.irrigate_gradki
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn_gradki
  mode: single
- id: '1745090889148'
  alias: Автополив. Кусты.
  description: ''
  triggers:
  - trigger: time
    at: input_datetime.irrigate_kust
  conditions:
  - condition: time
    weekday:
    - sat
    - tue
    - thu
  - condition: state
    entity_id: input_boolean.irrigate_kust
    state: 'on'
  - condition: state
    entity_id: input_boolean.irrigate_skip
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn_kust_facade
  - wait_for_trigger:
    - trigger: state
      entity_id:
      - switch.irrigate_lawn_kust_facade
      to: 'off'
    continue_on_timeout: false
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.irrigate_lawn_kust_terrace
  mode: single
- id: '1746777782832'
  alias: Шторы. Открытие Кухня
  description: ''
  triggers:
  - entity_id:
    - input_boolean.curtain_kitchen
    to: 'off'
    from: 'on'
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data:
      position: 93
    target:
      entity_id: cover.lumi_lumi_curtain_cover_3
    action: cover.set_cover_position
  mode: single
- id: '1746795547403'
  alias: Калитка. Закрытие
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
  conditions:
  - condition: state
    entity_id: input_boolean.kalitka_auto
    state: 'on'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_12
  mode: single
- id: '1746795687067'
  alias: Калитка. Открытие
  description: ''
  triggers:
  - trigger: time
    at: 07:00:00
  conditions:
  - condition: state
    entity_id: input_boolean.alarm_enabled
    state: 'off'
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_12
  mode: single
- id: '1747766164442'
  alias: Ворота app
  description: ''
  triggers:
  - event_type: ios.action_fired
    event_data:
      actionID: 107888C7-25ED-487D-AFF4-BB42BE6C7D33
    trigger: event
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.tasmota_tasmota4
  mode: single
