# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/ha-yandex-icons/yandex-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# mDNS service in /etc/avahi/service/ha.service
# homekit:
#   port: 51827
# For nginx https proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1


notify:
  - name: me
    platform: telegram
    chat_id: 623375633

yandex_station:
  include:
    - name: Кондиционер
      current_temperature: "{{ states('sensor.zigbee_temperature') }}"

climate:
  - platform: generic_thermostat
    name: Отопление
    heater: input_boolean.boiler
    target_sensor: sensor.zigbee_temperature
    min_temp: 20
    max_temp: 25
    cold_tolerance: 1
    hot_tolerance: 0

counter:
  water:
    initial: 0
    step: 10

rest_command:
  ping_autopolive:
    url: "http://192.168.0.106/update"
    method: GET
    timeout: 2

template:
  - sensor: 
    - name: Потребление воды
      unit_of_measurement: L
      device_class: water
      state_class: total_increasing
      state: "{{states('counter.water') }}"
    - name: Потребление электроэнергии
      unit_of_measurement: Wh
      device_class: energy
      state_class: total
      state: "{{states('input_number.energy_total') }}"
    - name: Потребление электроэнергии (кВт) 
      unit_of_measurement: MWh 
      state_class: total_increasing 
      device_class: energy 
      state: "{{ (states('input_number.energy_total') | float / 1000) | round(1) }}"
    - name: Глубина септика
      unit_of_measurement: см 
      state: "{{ 300 - (states('sensor.tze284_kyyu8rbj_ts0601_glubina_zhidkosti') | int) }}"

group:
  ignored_entities:
    entities:
      - switch.tasmota_3
      - sensor.tasmota_am2301_temperature
      - sensor.tasmota_am2301_humidity
      - camera.zhorik_map
      - camera.zhorik_map_1
 
sensor:
- platform: template
  sensors:
    unavailable_entities:
        friendly_name: Недоступные устройства
        value_template: >
          {{ states | selectattr('state','in',['unavailable']) | rejectattr('domain','eq','group') | rejectattr('entity_id', 'in', state_attr('group.ignored_entities', 'entity_id')) | rejectattr('entity_id', 'search', 'zhorik') | list | count }}
        attribute_templates:
          entities: >
            {{ states|selectattr('state','in', ['unavailable']) | rejectattr('domain','eq','group') | rejectattr('entity_id', 'in', state_attr('group.ignored_entities','entity_id')) | rejectattr('entity_id', 'search', 'zhorik') | map(attribute='name') | list }}

input_select:
  irrigate_zone:
    name: Irrigate zone
    options:
      - 1
      - 2
      - 3
      - 4

input_datetime:
  irrigate_evning:
    name: Автополив вечером
    has_date: false
    has_time: true
  irrigate_morning:
    name: Автополив газона утром время
    has_date: false
    has_time: true
  irrigate_gas_evning:
    name: Автополив газона вечером время
    has_date: false
    has_time: true
  irrigate_gradki:
    name: Автополив грядок время
    has_date: false
    has_time: true
  irrigate_kust:
    name: Автополив кусты время
    has_date: false
    has_time: true
  fumigator_time:
    name: Фумигатор время
    has_date: false
    has_time: true

input_boolean:
  irrigate_evning:
    name: Автополив вечером
    icon: mdi:water-pump
  irrigate_morning:
    name: Автополив утром
    icon: mdi:water-pump
  irrigate_evning_gas:
    name: Автополив газона вечером
    icon: mdi:water-pump
  irrigate_morning_gas:
    name: Автополив газона утром
    icon: mdi:water-pump
  irrigate_gradki:
    name: Автополив грядок
    icon: mdi:water-pump
  irrigate_kust:
    name: Автополив кустов
    icon: mdi:water-pump
  irrigate_skip_evning:
    name: Автополив пропустить вечером
    icon: mdi:toggle-switch-outline
  irrigate_skip_morning:
    name: Автополив пропустить утром
    icon: mdi:toggle-switch-outline
  irrigate_skip:
    name: Автополив пропустить
    icon: mdi:toggle-switch-outline
  irrigate_availeble:
    name: Автополив доступен
    icon: mdi:toggle-switch-outline
  clean_kitchen:
    name: Уборка кухни
    icon: mdi:toggle-switch-outline
  boiler:
    name: Котел
    icon: mdi:toggle-switch-outline
  fumigator_enabled:
    name: Фумигатор
    icon: mdi:toggle-switch-outline
  curtain_kitchen:
    name: Шторы кухня (input)
    icon: mdi:curtains-closed
  curtain_hall:
    name: Шторы зал (input)
    icon: mdi:curtains-closed
  curtain_bedroom:
    name: Шторы спальня (input)
    icon: mdi:curtains-closed
  alarm_enabled:
    name: Охрана (input)
    icon: mdi:shield-lock-outline
  kalitka_auto:
    name: Автокалитка (input)
    icon: mdi:shield-lock-outline

input_text:
  irrigation_active_zone:
    initial: inactive
  zone_action_result:
    name: "Zone Action Result"

##################################
# Irrigation zone time selection   #
##################################
input_number:
  irrigate_timer_1:
    name: Timer zone1
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  irrigate_timer_2:
    name: Timer zone2
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  irrigate_timer_morning_2:
    name: Timer morninr zone2
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  irrigate_timer_evening_2:
    name: Timer evening zone2
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  irrigate_timer_3:
    name: Timer zone3
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  irrigate_timer_4:
    name: Timer zone4
    min: 1
    max: 60
    step: 1
    unit_of_measurement: мин.
    icon: mdi:timer-cog
  fumigator_timer:
    name: Фумигатор время
    min: 1
    max: 8
    step: 1
    unit_of_measurement: ч.
    icon: mdi:timer-cog
  energy_total:
    name: Электороэнергия
    min: 0
    max: 150000
    unit_of_measurement: Wh
    icon: mdi:lightning-bolt

################################################
# Selected Sprinkler switch script & timer #
################################################
timer:
  irrigation_time_remaining:
    name: Remaining Time
    duration: "00:00:00"

switch:
  - platform: template
    switches:
      irrigate_lawn:
        friendly_name: "Sprinkler On/Off"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_on
          - service: timer.start
            target:
              entity_id: timer.irrigation_time_remaining
            data:
              duration: "{{ states('input_number.irrigate_timer_' ~ states('input_select.irrigate_zone')) | int  * 60 }}"
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: "{{ states('input_select.irrigate_zone') }}"
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_off
          - service: timer.finish
            target:
              entity_id: timer.irrigation_time_remaining
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: inactive
        icon_template: >-
          mdi:water-pump
      irrigate_lawn_gas:
        friendly_name: "Sprinkler On/Off Газон"
        turn_on:
          - service: timer.start
            target:
              entity_id: timer.irrigation_time_remaining
            data:
              duration: "{{ states('input_number.irrigate_timer_2') | int  * 60 }}"
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: "2"
          - service: script.turn_on
            data:
              entity_id: script.irrigation_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_off
          - service: timer.finish
            target:
              entity_id: timer.irrigation_time_remaining
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: inactive
      irrigate_lawn_gradki:
        friendly_name: "Sprinkler On/Off Грядки"
        turn_on:
          - service: timer.start
            target:
              entity_id: timer.irrigation_time_remaining
            data:
              duration: "{{ states('input_number.irrigate_timer_1') | int  * 60 }}"
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: "1"
          - service: script.turn_on
            data:
              entity_id: script.irrigation_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_off
          - service: timer.finish
            target:
              entity_id: timer.irrigation_time_remaining
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: inactive
      irrigate_lawn_kust_facade:
        friendly_name: "Sprinkler On/Off Кусты фасад"
        turn_on:
          - service: timer.start
            target:
              entity_id: timer.irrigation_time_remaining
            data:
              duration: "{{ states('input_number.irrigate_timer_4') | int  * 60 }}"
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: "4"
          - service: script.turn_on
            data:
              entity_id: script.irrigation_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_off
          - service: timer.finish
            target:
              entity_id: timer.irrigation_time_remaining
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: inactive
      irrigate_lawn_kust_terrace:
        friendly_name: "Sprinkler On/Off Кусты террсаса"
        turn_on:
          - service: timer.start
            target:
              entity_id: timer.irrigation_time_remaining
            data:
              duration: "{{ states('input_number.irrigate_timer_3') | int  * 60 }}"
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: "3"
          - service: script.turn_on
            data:
              entity_id: script.irrigation_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.irrigation_off
          - service: timer.finish
            target:
              entity_id: timer.irrigation_time_remaining
          - service: input_text.set_value
            target:
              entity_id: input_text.irrigation_active_zone
            data:
              value: inactive
        
